name: food_ui
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  smooth_page_indicator: ^1.2.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  get_storage: ^2.1.1
  image_picker: ^1.1.2
  cloud_firestore: ^5.6.6
  cached_network_image: ^3.4.1
  firebase_crashlytics: ^4.3.5
  url_launcher: ^6.1.10
  flutter_image_compress: ^2.0.0
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  badges: ^3.1.2
  shared_preferences: ^2.5.3
  emoji_picker_flutter: ^4.3.0
  awesome_notifications: ^0.10.1
  hive_ce_flutter: ^2.3.0
  curved_navigation_bar: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  hive_ce_generator: ^1.9.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo/
    - assets/icon/ # Include icon folder for notification icon

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
